# Generated by Django 3.2.10 on 2022-06-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
      #  migrations.CreateModel(
       #     name='Product',
        #    fields=[
          #      ('name', models.CharField(blank=True, max_length=255, null=True)),
         #       ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
           #     ('url_image', models.CharField(blank=True, max_length=255, null=True)),
            #    ('price', models.FloatField(blank=True, null=True)),
             #   ('discount', models.IntegerField(blank=True, null=True)),
   #         ],
    #        options={
        #        'managed': False,
     ##           'db_table': 'product',
       #     },
       # ),
    ]
